config/routes.rb
Project1::Application.routes.draw do
  get "comments/new"
  get "sessions/new"

  resources :users, :only => [:new, :create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy, :vote]
  resources :comments, :only => [:create, :destroy]
  resources :votes, :only => [:create, :vote_comments]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/comments', :to => 'comments#new'
  match '/votes', :to => 'votes#create'

  match 'users/create_admin', :to =>'users#create_admin'

  resources :pages do
            collection do
            post :search
            post :home
            end
  end

  resources :users do
            collection do
            post :create_admin
            end
  end

  get "pages/home"
  get "users/new"
  get "microposts/new"
  get "votes/new"

  root :to => 'pages#home'

end

app/views/layouts/_header.html.erb
<header>
  <%= link_to root_path %>
  <nav >
  <ul>

              <% if signed_in? %>
                      <li><%=button_to current_user.name, current_user, :class => 'menu_button', :size => current_user.name.length * 10 , :method => :get%></li>
              <% end %>
            <li><%= button_to "Home", root_path, :class => 'menu_button'%></li>

            <% if signed_in? %>
                    <li><%= button_to "Settings", edit_user_path(current_user), :class => 'menu_button', :method => :get %></li>
                    <li><%= button_to "Users", users_path, :class => 'menu_button', :method => :get %></li>

              <% end %>
              <% if signed_in? %>
                      <li><%= button_to "Sign Out", signout_path, :class => 'menu_button' %>
              <% else %>
                      <li><%= button_to "Sign In", signin_path, :class => 'menu_button' %></li>
                       <li> <%= button_to "Sign Up", signup_path, :class => 'menu_button' %> </li>
              <% end %>
    </ul>

    </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
        <head>
                <title><%= title %></title>
                <!--[if lt IE 9]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
                <![endif]-->
                <%= javascript_include_tag :jquery %>
                <%= javascript_include_tag :rails %>
                <%= javascript_include_tag :application %>
                <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
                <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
                <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
                 <%= stylesheet_link_tag 'custom', :media => 'screen' %>

         </head>
         <body>

                 <div class="container">
                         <div class="livebook"> <h1>LiveBook</h1></div>
                         <div class="menu">
                                 <%= render 'layouts/header' %>
                         </div>
                         <section >
                         <%= yield %>
                         </section>
                 </div>
                 <div class="flash">
                         <% flash.each do |key, msg| %>
                         <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_ #{key}" %>
                         <% content_tag :script, :type => "text/javascript" do %>
                                 setTimeout("new Effect.Fade('notice_<%= key %>');", 15000);
                         <% end %> 
                         <% end %>
                 
                 </div>

         </body>
</html>